name: cinenight
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_ui_auth: ^3.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  go_router: ^16.2.4
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  flutter_riverpod: ^3.0.2
  riverpod_annotation: ^3.0.3
  http: ^1.5.0
  json_annotation: ^4.9.0
  envied: ^1.3.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.2
  riverpod_generator: ^3.0.3
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  envied_generator: ^1.3.1
  test: ^1.26.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
    - assets/images/namelesslogo.png
